---
version: '1.1.0'
type: 'tooling'
component:
  name: 'pycfmodel'
  owner:
    - 'Security'
  description: 'A python model for Cloud Formation scripts'
  serviceClass: economy-class
  personalDataHandling: none
  soxScope: False
  paymentProcessing: False