name: Test Docs

on: push

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    name: Test Docs

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
        with:
          enable-cache: true

      - name: Setup python
        run: uv python install 3.10

      - run: make install-docs

      - run: make test-docs
