name: Version Consistency Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  version-check:
    name: Version Consistency Check
    permissions:
      contents: read
    runs-on: ubuntu-latest-small
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Check Version Consistency
        uses: Skyscanner/version-consistency-check@v1
        with:
          fail-on-inconsistency: true
